export const persons = [
{ "id": 1, "name": "Baking Soda", "email": "$2.84", "position": "Seo" },
{ "id": 2, "name": "Oil - Sesame", "email": "$9.80", "position": "Seo" },
{ "id": 3, "name": "Beans - Fine", "email": "$4.93", "position": "Seo" },
{ "id": 4, "name": "Wine - White, Ej", "email": "$1.20", "position": "Seo" },
{ "id": 5, "name": "Beef - Ground Lean Fresh", "email": "$6.98", "position": "Seo" },
{ "id": 6, "name": "Lemonade - Black Cherry, 591 Ml", "email": "$1.22", "position": "Seo" },
{ "id": 7, "name": "Edible Flower - Mixed", "email": "$7.06", "position": "Seo" },
{ "id": 8, "name": "Bread - Bistro White", "email": "$6.62", "position": "Seo" },
{ "id": 9, "name": "Bread - Multigrain Oval", "email": "$3.98", "position": "Seo" },
{ "id": 10, "name": "Goat - Whole Cut", "email": "$6.83", "position": "Seo" },
{ "id": 11, "name": "Mussels - Cultivated", "email": "$1.18", "position": "Seo" },
{ "id": 12, "name": "Carbonated Water - Wildberry", "email": "$9.57", "position": "Seo" },
{ "id": 13, "name": "Soup - Campbells, Classic Chix", "email": "$5.31", "position": "Seo" },
{ "id": 14, "name": "Sugar - Brown", "email": "$8.41", "position": "Seo" },
{ "id": 15, "name": "Silicone Parch. 16.3x24.3", "email": "$8.34", "position": "Seo" },
{ "id": 16, "name": "Bamboo Shoots - Sliced", "email": "$1.14", "position": "Seo" },
{ "id": 17, "name": "Table Cloth 91x91 Colour", "email": "$0.23", "position": "Seo" },
{ "id": 18, "name": "Cumin - Whole", "email": "$9.76", "position": "Seo" },
{ "id": 19, "name": "Squid U5 - Thailand", "email": "$4.46", "position": "Seo" },
{ "id": 20, "name": "Mustard - Dijon", "email": "$6.47", "position": "Seo" },
{ "id": 21, "name": "Chocolate Bar - Coffee Crisp", "email": "$1.77", "position": "Seo" },
{ "id": 22, "name": "Garam Marsala", "email": "$0.08", "position": "Seo" },
{ "id": 23, "name": "Cheese - Cream Cheese", "email": "$5.42", "position": "Seo" },
{ "id": 24, "name": "Steel Wool S.o.s", "email": "$3.81", "position": "Seo" },
{ "id": 25, "name": "Beef - Tongue, Cooked", "email": "$2.07", "position": "Seo" }];